name: Publish to PoshTest Gallery
on: workflow_dispatch
jobs:
  PublishToPoshTestGallery:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Modules
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module -Name Mailozaurr -RequiredVersion "0.0.10"
          Install-Module -Name platyPs
      - name: Ensure nuget is set up properly
        uses: fabriciomurta/ensure-nuget-source@v1
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: 5.x
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9
      - name: Remove Dashes from Prerelease String
        id: cleanversion
        run: |
          $CleanVersion = "${{ steps.gitversion.outputs.NuGetPreReleaseTagV2 }}" -replace "-",""
          $CleanVersion = "${{ steps.gitversion.outputs.MajorMinorPatch }}" + "-" + $CleanVersion
          Write-Output -InputObject "::set-output name=cleanversion::$CleanVersion"
      - name: Update Changelog for Release
        id: changelog
        uses: natescherer/changelog-management-action@main
        with:
          mode: release
          releaseversion: ${{ steps.cleanversion.outputs.cleanversion }}
      - name: Update PowerShell Metadata
        uses: natescherer/update-powershell-metadata-action@v1.0.0
        with:
          path: src
          version: ${{ steps.cleanversion.outputs.cleanversion }}
          copyright: (c) YYYY Nate Scherer. All rights reserved.
          releasenotes: ${{ steps.changelog.outputs.releasenotes }}
          functionstoexportpath: src\public
      - name: Generate Markdown Help Files
        run: |
          New-Item -Path "docs" -ItemType Directory  -ErrorAction SilentlyContinue | Out-Null
          Remove-Item -Path "docs\*" -Recurse -ErrorAction SilentlyContinue
          $ModulePath = (Get-ChildItem -Path "$env:GITHUB_WORKSPACE\src" -Include "*.psm1" -Recurse).FullName
          $ModuleName = Split-Path -Path $ModulePath -LeafBase
          Get-Module -Name $ModuleName -All | Remove-Module -Force -ErrorAction Ignore
          Import-Module -Name $ModulePath -Force -ErrorAction Stop
          New-MarkdownHelp -Module $ModuleName -OutputFolder "docs" -NoMetadata | Out-Null
      - name: Build 'out' Directory
        run: |
          Copy-Item -Path "$env:GITHUB_WORKSPACE\src" -Destination "$env:GITHUB_WORKSPACE\out" -Recurse
      - name: Create Documentation for Release
        uses: natescherer/markdown-to-html-with-github-style-action@v1
        with:
          path: README.md,CHANGELOG.md,docs
          outputpath: out
          matchpathstructure: true
      - name: Publish Module to PoshTestGallery
        uses: natescherer/publish-powershell-action@main
        with:
          token: ${{ secrets.POSHTESTGALLERY_TOKEN }}
          target: testgallery
          path: out